python inference.py \
    --prompt "Walking over stairs, first-person view, no background, no tree, blue sky and sun." \
    --condition "canny" \
    --video_path "data/channel_rgb.mp4" \
    --output_path "outputs/" \
    --video_length 50 \
    --smoother_steps 19 20 \
    --width 256 \
    --height 256 \
    --frame_rate 2 \
    --version v10 \
    --is_long_video